apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "applimits"
spec:
  limits:
    - type: "Container"
      max:
        memory: "256Mi"
        cpu: "300m"
      min:
        memory: "96Mi"
        cpu: "125m"
      default:
        memory: "128Mi"
        cpu: "200m"
