kind: Role 
apiVersion: rbac.authorization.k8s.io/v1 
metadata: 
  name: devops-role 
  namespace: devops-rbac 
rules: 
  - apiGroups: [""] 
    resources: ["pods"] 
    verbs: ["get", "list", "watch"]

