kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
metadata: 
  name: devops-rolebinding 
  namespace: devops-rbac 
subjects: 
  - kind: User 
    name: jim 
    namespace: devops-rbac 
roleRef: 
  kind: Role 
  name: devops-role 
  apiGroup: rbac.authorization.k8s.io

