# for MariaDB persistent Storage (via Helm)
# ----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/export/nfs/vol2
    server: nfs
  claimRef:
    name: pvc-mariadb
    namespace: wordpress-app

